//! Cross-IR export: translate TPT Lexicon IR into external standard formats.
//!
//! - [`to_tree_sitter_ast`]: JSON-like S-expression output
//! - [`to_lsp_document`]: LSP textDocument representation
//! - [`to_llvm_ir`]: simplified LLVM IR text output

use alloc::format;
use alloc::string::String;

use tpt_lexicon_ir::{IrForest, IrNode};

/// Convert an IR forest to a Tree-sitter-style S-expression AST.
///
/// Each node becomes an S-expression: `(type "content")`.
///
/// # Examples
///
/// ```
/// use tpt_lexicon_ir::{IrForest, IrNode};
/// use tpt_lexicon_translate::to_tree_sitter_ast;
///
/// let forest = IrForest::from_nodes(vec![
///     IrNode::code(b"let x = 1;"),
/// ]);
/// let ast = to_tree_sitter_ast(&forest);
/// assert!(ast.contains("code_0"));
/// assert!(ast.contains("let x = 1;"));
/// ```
pub fn to_tree_sitter_ast(forest: &IrForest<'_>) -> String {
    let mut out = String::from("(program");

    for (i, node) in forest.nodes().iter().enumerate() {
        out.push(' ');
        match node {
            IrNode::Text(bytes) => {
                let s = core::str::from_utf8(bytes).unwrap_or("<binary>");
                out.push_str(&format!("(text_{i} \"{s}\")"));
            }
            IrNode::Code(bytes) => {
                let s = core::str::from_utf8(bytes).unwrap_or("<binary>");
                out.push_str(&format!("(code_{i} \"{s}\")"));
            }
            IrNode::Structured(bytes) => {
                let s = core::str::from_utf8(bytes).unwrap_or("<binary>");
                out.push_str(&format!("(structured_{i} \"{s}\")"));
            }
            IrNode::List(indices) => {
                out.push_str(&format!("(list_{i}"));
                for &idx in indices {
                    out.push_str(&format!(" ref:{idx}"));
                }
                out.push(')');
            }
            IrNode::Reference(idx) => {
                out.push_str(&format!("(ref {idx})"));
            }
            IrNode::Compressed { rule_index, args } => {
                out.push_str(&format!("(compressed rule:{rule_index}"));
                for &arg in args {
                    out.push_str(&format!(" arg:{arg}"));
                }
                out.push(')');
            }
        }
    }

    out.push(')');
    out
}

/// Convert an IR forest to an LSP `textDocument` representation.
///
/// Produces a JSON-like string with node metadata suitable for LSP tooling.
pub fn to_lsp_document(forest: &IrForest<'_>) -> String {
    let mut out = String::from("{\"nodes\":[");

    for (i, node) in forest.nodes().iter().enumerate() {
        if i > 0 {
            out.push(',');
        }
        let kind = node.kind_name();
        let content = node
            .as_bytes()
            .and_then(|b| core::str::from_utf8(b).ok())
            .unwrap_or("");

        out.push_str(&format!(
            "{{\"index\":{i},\"kind\":\"{kind}\",\"content\":\"{}\"}}",
            escape_json_string(content),
        ));
    }

    out.push_str("]}");
    out
}

/// Convert an IR forest to simplified LLVM IR text.
///
/// Each code node becomes a function body; text nodes become comments.
pub fn to_llvm_ir(forest: &IrForest<'_>) -> String {
    let mut out = String::from("; Generated by TPT Lexicon translate\n\n");

    for (i, node) in forest.nodes().iter().enumerate() {
        match node {
            IrNode::Text(bytes) => {
                let s = core::str::from_utf8(bytes).unwrap_or("<binary>");
                out.push_str(&format!("; [text node {i}]\n; {s}\n\n"));
            }
            IrNode::Code(bytes) => {
                let s = core::str::from_utf8(bytes).unwrap_or("<binary>");
                out.push_str(&format!(
                    "define void @node_{i}() {{\n  ; {s}\n  ret void\n}}\n\n"
                ));
            }
            IrNode::Structured(bytes) => {
                let s = core::str::from_utf8(bytes).unwrap_or("<binary>");
                out.push_str(&format!("; [structured node {i}]\n; {s}\n\n"));
            }
            IrNode::List(indices) => {
                out.push_str(&format!(
                    "; [list node {i}] contains {len} items\n\n",
                    len = indices.len()
                ));
            }
            IrNode::Reference(idx) => {
                out.push_str(&format!("; [reference node {i}] -> node {idx}\n\n"));
            }
            IrNode::Compressed { rule_index, args } => {
                out.push_str(&format!(
                    "; [compressed node {i}] rule={rule_index} args={:?}\n\n",
                    args,
                ));
            }
        }
    }

    out
}

/// Escape a string for inclusion in a JSON string value.
fn escape_json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c < '\x20' => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::VERSION;
    use alloc::vec;

    #[test]
    fn tree_sitter_ast_basic() {
        let forest =
            IrForest::from_nodes(vec![IrNode::code(b"let x = 1;"), IrNode::text(b"comment")]);
        let ast = to_tree_sitter_ast(&forest);
        assert!(ast.starts_with("(program"));
        assert!(ast.contains("code_0"));
        assert!(ast.contains("text_1"));
        assert!(ast.ends_with(')'));
    }

    #[test]
    fn lsp_document_basic() {
        let forest = IrForest::from_nodes(vec![IrNode::code(b"fn main() {}")]);
        let doc = to_lsp_document(&forest);
        assert!(doc.contains("\"nodes\""));
        assert!(doc.contains("\"kind\":\"code\""));
        assert!(doc.contains("fn main() {}"));
    }

    #[test]
    fn llvm_ir_basic() {
        let forest =
            IrForest::from_nodes(vec![IrNode::code(b"return 42;"), IrNode::text(b"header")]);
        let ir = to_llvm_ir(&forest);
        assert!(ir.contains("define void @node_0()"));
        assert!(ir.contains("; [text node 1]"));
    }

    #[test]
    fn escape_json_special_chars() {
        assert_eq!(escape_json_string("hello"), "hello");
        assert_eq!(escape_json_string("a\"b"), "a\\\"b");
        assert_eq!(escape_json_string("a\nb"), "a\\nb");
        assert_eq!(escape_json_string("a\\b"), "a\\\\b");
    }

    #[test]
    fn empty_forest() {
        let forest = IrForest::new();
        assert_eq!(to_tree_sitter_ast(&forest), "(program)");
        assert_eq!(to_lsp_document(&forest), "{\"nodes\":[]}");
    }

    #[test]
    fn tree_sitter_compressed_node() {
        let forest = IrForest::from_nodes(vec![IrNode::Compressed {
            rule_index: 0,
            args: vec![1, 2],
        }]);
        let ast = to_tree_sitter_ast(&forest);
        assert!(ast.contains("compressed"));
        assert!(ast.contains("rule:0"));
    }

    #[test]
    fn lsp_json_escaping() {
        let forest = IrForest::from_nodes(vec![IrNode::text(b"say \"hello\"")]);
        let doc = to_lsp_document(&forest);
        assert!(doc.contains("say \\\"hello\\\""));
    }

    #[test]
    fn llvm_ir_list_node() {
        let forest = IrForest::from_nodes(vec![IrNode::list(vec![0, 1, 2])]);
        let ir = to_llvm_ir(&forest);
        assert!(ir.contains("3 items"));
    }

    #[test]
    fn version_is_nonempty() {
        assert!(!VERSION.is_empty());
    }
}
